spring:
 application: 
  name: Spring-ai-assistant
 ai:
  openai:
   api-key: ${OPENAI_API_KEY}
   audio:
    transcription:
      base-url: https://api.openai.com
      options:
       model: whisper-1
       response-format: json

img:
 model-type: dall-e-2 ##Deafult is dall-e-2
 height: 512
 width: 512
 quality: hd  ##Default is standard
 style: natural ##Deafult is vivid
 number-of-img: 1