spring:
 application: 
  name: Spring-ai-assistant
 ai:
  openai:
   api-key: ${OPENAI_API_KEY}

img:
 model-type: dall-e-2 ##Deafult is dall-e-2
 height: 512
 width: 512
 quality: hd  ##Default is standard
 style: natural ##Deafult is vivid
 number-of-img: 1